//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to templecampfire.png
        ///size:332,68
        ///filter:MipMap,MipMap
        ///pma:true
        ///scale:2.0
        ///01
        ///bounds:2,2,64,64
        ///02
        ///bounds:68,2,64,64
        ///03
        ///bounds:134,2,64,64
        ///04
        ///bounds:200,2,64,64
        ///05
        ///bounds:266,2,64,64
        ///.
        /// </summary>
        internal static string campfire_atlas {
            get {
                return ResourceManager.GetString("campfire atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] campfire_img {
            get {
                object obj = ResourceManager.GetObject("campfire img", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;skeleton&quot;: { &quot;hash&quot;: &quot;lCsDPQp6akI&quot;, &quot;spine&quot;: &quot;4.2.35&quot;, &quot;images&quot;: &quot;../char sprites/&quot;, &quot;audio&quot;: &quot;&quot; },
        ///&quot;bones&quot;: [
        ///	{ &quot;name&quot;: &quot;root&quot;, &quot;scaleX&quot;: 4, &quot;scaleY&quot;: 4 },
        ///	{ &quot;name&quot;: &quot;bone&quot;, &quot;parent&quot;: &quot;root&quot;, &quot;y&quot;: 9 }
        ///],
        ///&quot;slots&quot;: [
        ///	{ &quot;name&quot;: &quot;idle-battle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run right&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run down&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run left&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run up&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;idle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;hitbox&quot;, &quot;bone&quot;: &quot;bone&quot;, &quot;attachmen [rest of string was tru....
        /// </summary>
        internal static string campfire_json {
            get {
                return ResourceManager.GetString("campfire json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savedit.png
        ///size:704,217
        ///filter:Linear,Linear
        ///pma:true
        ///armbacklower
        ///bounds:490,38,28,67
        ///offsets:273,249,800,747
        ///armbackupper
        ///bounds:630,7,38,72
        ///offsets:284,302,800,747
        ///rotate:90
        ///armfrontlower
        ///bounds:595,47,37,79
        ///offsets:370,230,800,747
        ///armfrontupper
        ///bounds:634,50,50,76
        ///offsets:357,289,800,747
        ///earback
        ///bounds:238,38,92,177
        ///offsets:222,309,800,747
        ///earfront
        ///bounds:2,2,121,213
        ///offsets:406,247,800,747
        ///footback
        ///bounds:553,125,90,38
        ///offsets:249,130,800,747
        ///rotate:90
        ///footfront
        ///bounds:520, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chara_atlas {
            get {
                return ResourceManager.GetString("chara atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chara_img {
            get {
                object obj = ResourceManager.GetObject("chara img", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;skeleton&quot;: { &quot;hash&quot;: &quot;lCsDPQp6akI&quot;, &quot;spine&quot;: &quot;4.2.35&quot;, &quot;images&quot;: &quot;../char sprites/&quot;, &quot;audio&quot;: &quot;&quot; },
        ///&quot;bones&quot;: [
        ///	{ &quot;name&quot;: &quot;root&quot;, &quot;scaleX&quot;: 4, &quot;scaleY&quot;: 4 },
        ///	{ &quot;name&quot;: &quot;bone&quot;, &quot;parent&quot;: &quot;root&quot;, &quot;y&quot;: 9 }
        ///],
        ///&quot;slots&quot;: [
        ///	{ &quot;name&quot;: &quot;idle-battle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run right&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run down&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run left&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run up&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;idle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;hitbox&quot;, &quot;bone&quot;: &quot;bone&quot;, &quot;attachmen [rest of string was tru....
        /// </summary>
        internal static string chara_json {
            get {
                return ResourceManager.GetString("chara json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savedthepheasant.png
        ///size:327,522
        ///filter:Linear,Linear
        ///pma:true
        ///footlower
        ///bounds:171,17,40,27
        ///offsets:302,132,800,747
        ///footupper
        ///bounds:213,4,40,27
        ///offsets:348,111,800,747
        ///rotate:90
        ///head
        ///bounds:242,2,67,57
        ///offsets:235,257,800,747
        ///leglower
        ///bounds:2,15,29,85
        ///offsets:313,151,800,747
        ///rotate:90
        ///legupper
        ///bounds:89,16,28,80
        ///offsets:359,131,800,747
        ///rotate:90
        ///neck
        ///bounds:242,61,83,111
        ///offsets:245,171,800,747
        ///torso
        ///bounds:2,174,323,346
        ///offsets:244,158,800,747
        ///winglower
        ///bounds:2,46,119,126
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pheasant_atlas {
            get {
                return ResourceManager.GetString("pheasant atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pheasant_img {
            get {
                object obj = ResourceManager.GetObject("pheasant img", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;skeleton&quot;: { &quot;hash&quot;: &quot;lCsDPQp6akI&quot;, &quot;spine&quot;: &quot;4.2.35&quot;, &quot;images&quot;: &quot;../char sprites/&quot;, &quot;audio&quot;: &quot;&quot; },
        ///&quot;bones&quot;: [
        ///	{ &quot;name&quot;: &quot;root&quot;, &quot;scaleX&quot;: 4, &quot;scaleY&quot;: 4 },
        ///	{ &quot;name&quot;: &quot;bone&quot;, &quot;parent&quot;: &quot;root&quot;, &quot;y&quot;: 9 }
        ///],
        ///&quot;slots&quot;: [
        ///	{ &quot;name&quot;: &quot;idle-battle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run right&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run down&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run left&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run up&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;idle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;hitbox&quot;, &quot;bone&quot;: &quot;bone&quot;, &quot;attachmen [rest of string was tru....
        /// </summary>
        internal static string pheasant_json {
            get {
                return ResourceManager.GetString("pheasant json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char sprites.png
        ///size:1856,362
        ///filter:MipMap,MipMap
        ///pma:true
        ///scale:4.0
        ///empty/01
        ///bounds:550,81,1,1
        ///flags/red/01
        ///bounds:506,2,76,76
        ///offsets:40,28,128,128
        ///flags/red/02
        ///bounds:96,2,80,76
        ///offsets:40,28,128,128
        ///flags/red/03
        ///bounds:1778,206,76,72
        ///offsets:40,28,128,128
        ///flags/red/04
        ///bounds:1778,132,76,72
        ///offsets:40,28,128,128
        ///flags/red/05
        ///bounds:1778,50,80,72
        ///offsets:40,28,128,128
        ///rotate:90
        ///player/boy/idle/01
        ///bounds:584,2,80,84
        ///offsets:16,20,128,128
        ///rotate:90
        ///player/boy/idle/02
        ///bounds:1670,194,80,80
        ///offsets:16,20,12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string player_atlas {
            get {
                return ResourceManager.GetString("player atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] player_img {
            get {
                object obj = ResourceManager.GetObject("player img", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;skeleton&quot;: { &quot;hash&quot;: &quot;lCsDPQp6akI&quot;, &quot;spine&quot;: &quot;4.2.35&quot;, &quot;images&quot;: &quot;../char sprites/&quot;, &quot;audio&quot;: &quot;&quot; },
        ///&quot;bones&quot;: [
        ///	{ &quot;name&quot;: &quot;root&quot;, &quot;scaleX&quot;: 4, &quot;scaleY&quot;: 4 },
        ///	{ &quot;name&quot;: &quot;bone&quot;, &quot;parent&quot;: &quot;root&quot;, &quot;y&quot;: 9 }
        ///],
        ///&quot;slots&quot;: [
        ///	{ &quot;name&quot;: &quot;idle-battle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run right&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run down&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run left&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run up&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;idle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;hitbox&quot;, &quot;bone&quot;: &quot;bone&quot;, &quot;attachmen [rest of string was tru....
        /// </summary>
        internal static string player_json {
            get {
                return ResourceManager.GetString("player json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slime.png
        ///size:154,486
        ///filter:MipMap,MipMap
        ///pma:true
        ///scale:4.0
        ///jellyanim/atkd and idle/01
        ///bounds:2,186,120,108
        ///offsets:48,44,216,208
        ///jellyanim/atkd and idle/02
        ///bounds:2,2,132,92
        ///offsets:44,44,216,208
        ///jellyanim/atkd and idle/03
        ///bounds:2,96,140,88
        ///offsets:40,44,216,208
        ///jellyanim/atkd and idle/04
        ///bounds:80,324,160,72
        ///offsets:28,44,216,208
        ///rotate:90
        ///jellyanim/atkd and idle/05
        ///bounds:2,296,188,76
        ///offsets:16,44,216,208
        ///rotate:90
        ///.
        /// </summary>
        internal static string slime_atlas {
            get {
                return ResourceManager.GetString("slime atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] slime_img {
            get {
                object obj = ResourceManager.GetObject("slime img", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;skeleton&quot;: { &quot;hash&quot;: &quot;lCsDPQp6akI&quot;, &quot;spine&quot;: &quot;4.2.35&quot;, &quot;images&quot;: &quot;../char sprites/&quot;, &quot;audio&quot;: &quot;&quot; },
        ///&quot;bones&quot;: [
        ///	{ &quot;name&quot;: &quot;root&quot;, &quot;scaleX&quot;: 4, &quot;scaleY&quot;: 4 },
        ///	{ &quot;name&quot;: &quot;bone&quot;, &quot;parent&quot;: &quot;root&quot;, &quot;y&quot;: 9 }
        ///],
        ///&quot;slots&quot;: [
        ///	{ &quot;name&quot;: &quot;idle-battle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run right&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run down&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run left&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;run up&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;idle&quot;, &quot;bone&quot;: &quot;bone&quot; },
        ///	{ &quot;name&quot;: &quot;hitbox&quot;, &quot;bone&quot;: &quot;bone&quot;, &quot;attachmen [rest of string was tru....
        /// </summary>
        internal static string slime_json {
            get {
                return ResourceManager.GetString("slime json", resourceCulture);
            }
        }
    }
}
